### PR TITLE
Quadratic stress-strain relation in Python elasticity solver

### PR DESCRIPTION
**Pull request by ketch**
This adds an option to use a quadratic stress-strain relation in the Python version (only) of the nonlinear elasticity solver.  Previously the only relation available was exponential, which is still the default.  I'm using the quadratic relation for a chapter in the Riemann solvers book.

The choice of which relation to use is controlled by setting `state.problem_data['stress relation']` to either `exponential` (default) or `quadratic`.

The solver could be adapted to other relations without modifying this file by just overriding `sigma()` and `sigmap()`.

### CODE REVIEW

**Comment by mandli** [comment]
This may be a bit pedantic but I was wondering if there was any reason we may not want to have an underscore rather than the space in the key.  Everything else looks good to me.

**Comment by mandli** [comment]
Something before I forget, I think we should make a policy to remove the copyright statements from all the source as almost all are outdated and they are not really needed anymore.  Maybe we can post this suggestion to claw-dev and if no one responds go through and remove all of these for those we know (cannot really for people we do not have explicit permission from I think).

**Comment by ketch** [comment]
>I was wondering if there was any reason we may not want to have an underscore rather than the space in the key.

Is there a reason to prefer one or the other?

>we should make a policy to remove the copyright statements

Yes, I opened an issue.  Aall those statements that I can find belong to @ketch or @mandli.

**Comment by mandli** [comment]
>> I was wondering if there was any reason we may not want to have an underscore rather than the space in the key.

> Is there a reason to prefer one or the other?

I could think of a reason to use the space as it is more readable and could lead to nice labels if you wanted to do display the keys.  On the other hand if you wanted to specify a key on the command line an escape would be needed.  I don't actually have a case currently where this might be a problem but we in the future allowed specification of `problem_data` via the command line this would start to become a nuisance.  

Just to be clear I am more thinking out loud and do not have a strong opinion on this.

**Comment by ketch** [comment]
Okay, you convinced me and I've made the change.

**Pull request merged**
