### PR TITLE
Better traffic solvers

### PR DESCRIPTION
**Pull request by ketch**
This is a complete rework of the variable speed limit Riemann solver.  I have compared the old solver with the new one (and one intermediate version) here:

https://gist.github.com/ad1b6459fb3debad86a3760edcbd81de

The solver proposed in this PR is labeled 'q-wave' in the plots there.

The **old f-wave solver** (labeled 'old' in the comparison notebook) gives unphysical results (outside the [0,1] range) for some situations involving transonic shocks.  The resulting method does not converge to the correct solution in those situations.  This is due to an incorrect determination of the direction the shock should travel; the old solver simply used the average of the characteristic speeds to determine this.  This solver also exhibits a one-cell entropy glitch.

In the first commit in this PR, I replaced that determination with the correct one based on conservation.  The resulting (**new f-wave**) solver is labeled 'New' in the comparison notebook; it seems to give physical results that always converge to the correct solution as far as I have tested.  However, it suffers from a one-cell entropy glitch in the case of transonic rarefactions.

I have written a new solver (the one that actually appears in this PR, in the last commit) based on determination of the exact Riemann solution (including 8 different cases altogether).  This solver sets the fluctuations to those given by the exact solution.  For the second-order corrections it uses a single wave carrying the full jump in q and with the Rankine-Hugoniot shock speed.  This is of course not correct; I haven't investigated yet whether it can still be proved second order accurate like many similar solvers can.  It avoids the entropy glitch of the f-wave solvers and seems to give similarly or more accurate results in general (including all cases I've tested).

I have done all this in the "tracer" solver since I was working on that when I started.  If we agree that the new q-wave solver is best, I can replace the non-tracer version also with that.

### CODE REVIEW

**Comment by mandli** [comment]
This looks good to me.  Are you ready to have this merged or is this still [WIP] so as to address your comment about second order?

**Comment by ketch** [comment]
I updated the gist to include all the solvers and a Makefile.  If you want to test things yourself, clone the gist, run make, and it should all work.

**Comment by ketch** [comment]
Okay, this is ready to be merged.  I have made the q-wave solvers the new default.  Per @rjleveque's suggestion, I left the f-wave solver (without tracer, but with the correct transonic shock direction) as an alternative since it may be interesting to others.

**Comment by ketch** [comment]
@mandli No, I'm not planning to try and prove accuracy now.

**Pull request merged**
