### PR TITLE
Riemann Interactive

### PR DESCRIPTION
**Pull request by maojrs**
@rjleveque  & @ketch : Added riemann_interactive.py to produce interactive phase plane apps for shallow water eqs. and general linear two dimensional hyperbolic systems. Includes two test functions to show the functionality at the end of the file (html output optional). Another test can be seen in the ipynotebook:

http://nbviewer.ipython.org/github/maojrs/ipynotebooks/blob/master/interactive_test.ipynb

The left and right states as well as the time can be dragged around, and the solution will be automatically updated. Currently working on adding these apps into my acoustics notebook and the shallow water notebook by @rjleveque to incorporate into riemann_book. 

What do you guys think?

### CODE REVIEW

**Comment by ketch** [comment]
Nice!  This clearly took a lot of work.

Near the bottom of the file you have functions that say they are "tests".  Do you want to set those up to be automatically run using nose or doctest?  It wouldn't test the interactivity, but would at least ensure that the code runs.

**Comment by rjleveque** [comment]
Great!  

In the first set of plots for shallow water, the plots of depth and momentum are titled "Height h at time = t", etc.  How hard would it be to make the "t" be updated to the time selected in the x-t plot?  E.g. "... at time t = 1.2" or whatever.   But I'd say only do this if it's easy.

Also, personally I think "Depth h..." might be clearer than "Height h..." for SWE.

Thanks!!

**Comment by maojrs** [comment]
@ketch Yes those test should show if the code runs or not, though I have never done a nose or doctest. Do you have an example? I can set it up.

@rjleveque I think updating the time might be a bit difficult, since it requires sending the text as svg. I  might be possible, but I'm not even sure how or where to start. It might take some time to figure out. I can give it a try. Also, I already changed height to depth.

**Comment by ketch** [comment]
> Yes those test should show if the code runs or not, though I have never done a nose or doctest. Do you have an example? I can set it up.

Nose is a test harness; if you put "test" somewhere in the name of the function, then it will automatically run it: https://nose.readthedocs.org/en/latest/

Doctest is a built-in Python module that automatically runs any example code in your docstrings and checks the output against what is in the docstring.  I wrote a very short explanation of how to use it here:

http://www.davidketcheson.info/2015/05/14/write_docstrings.html
http://www.davidketcheson.info/2015/05/15/write_tests.html

**Comment by maojrs** [comment]
@ketch I think both tests should be running now.

**Comment by ketch** [comment]
I like that you have made the test names detectable by nose; thanks!

The "doctests" here don't make sense to me; I must not have explained what I meant.  The purpose of docstrings is to explain what functions do, and the purpose of using doctest is to make sure that the docstring explanation accurately reflects what the code does.  But you have created a "function" that has no purpose other than testing, and given it a "docstring" that has no purpose other than to run the function (as far as I can tell).  It seems circular.

I think it's okay to just delete `doctest_test`.  If you want to add examples in docstrings, I would add them to the functions that you expect a user to call.  But I never meant to imply that you had to do so.

I hope that makes sense and is helpful.

**Comment by maojrs** [comment]
@ketch I understand what you say. Writing appropriate doctest/docstring for the function might be a bit complicated, since the output of the functions is the interactive app. I removed the doctest_test and just left the nose tests.

**Comment by mandli** [comment]
What's the status of this PR?

**Comment by maojrs** [comment]
I added some recent changes by Randy and some suggestions in the formatting (font size, marker size and figure size). The final version can be seen here:

http://nbviewer.ipython.org/github/maojrs/ipynotebooks/blob/master/interactive_test.ipynb

I will also upload this notebook into the riemann_book repository.

**Comment by ketch** [comment]
It looks perfect now.  I can't wait to use this the next time I teach about Riemann solvers.

**Pull request merged**
