### PR TITLE
Shallow water solvers with bathymetry

### PR DESCRIPTION
**Pull request by ketch**
This PR adds 3 solvers:

1. A 1D f-wave solver for SW with bathymetry;
2. A 2D f-wave solver for SW with bathymetry (normal only);
3. Normal and transverse versions of the "augmented" 2D SW solvers from Geoclaw.  These solvers are made PyClaw-compatible by avoiding the use of modules, which f2py couldn't handle.  In the process of making this work, I removed some functionality, like mappings to the sphere and alternative solver versions. This could all be added back in; I was just trying to minimize the number of places where bugs could occur.

This is a replacement for #86, which has been waiting for over 2 years.  I know the long-term dream is to do a major overhaul of the Geoclaw solvers, but I don't want to wait on that before merging this.

### CODE REVIEW

**Comment by ketch** [comment]
The augmented solver here is used in https://github.com/clawpack/apps/blob/master/notebooks/pyclaw/beach.ipynb.

The 1D f-wave solver is tested in https://github.com/clawpack/pyclaw/pull/564.

**Comment by mandli** [comment]
Is the Python version and Fortran version consistent?  I vaguely recall that there may be a discrepancy that should be fixed.

**Comment by mandli** [comment]
Also thanks for resurrecting this.  My dream of refactoring the solver was too ambitious clearly.

**Comment by ketch** [comment]
The Python and Fortran 1D f-wave solvers do give slightly different answers, so they must be doing something different.  Let me take a look.

**Comment by ketch** [comment]
I ran a quick test and they are pretty close:

https://gist.github.com/ketch/8adf1ba9eb6e11ca8dfa996e7e1193a5

They are a bit different but both seem "correct" to me.

**Comment by mandli** [comment]
I can take a look, I may remember what I thought might have been wrong.

**Comment by mandli** [comment]
so the big difference between the two is that Python uses HLL like speeds and the Fortran uses the Roe speeds.  We should probably both change to using the Einfeldt speeds.  I can make the changes to both if you want.

**Comment by ketch** [comment]
That would be great.  After you make the changes just issue a PR against my shallow_fwave branch.

**Comment by ketch** [comment]
I reran the comparison and now things match up to roundoff (check the gist linked above; updated).

I guess we should make the same changes to the 2D fwave solver...

**Comment by mandli** [comment]
Ah sorry, should have checked that.  I can do that as well.

**Comment by mandli** [comment]
So I have something done but I was not sure if there was a test for the 2d solver.   From your previous comments it does not appear so but I wanted to make sure.  I am not confident right now that what I have is going to work as it required some significant reworking of what @ketch wrote.

**Comment by ketch** [comment]
You're right about the lack of a test.  I'll write one and try both versions.

**Comment by ketch** [comment]
I think we should go ahead and merge this so that https://github.com/clawpack/pyclaw/pull/564 will pass tests.  Neither one will pass without the other but I think we can be confident now that together they will pass (and every solver has a test or an app now).

**Comment by ketch** [comment]
Oh, but it's probably worth deleting the commented-out code first?  Sorry, I should have thought about that before I merged the secondary PR.

**Comment by ketch** [comment]
Okay, I've been checking more carefully and I was wrong.  Commit d765c00a8ad318b3e37e34660713824da3e7ba0b broke the 2D Riemann solver (it quickly generates NaNs for the test case).  It's not obvious to me what is wrong with those changes.  The older version gives results that look reasonable.

**Comment by mandli** [comment]
At the very least the determination of beta is not consistent.  I am hoping to get back to this soon so I can try and take a look again.

**Comment by ketch** [comment]
I think the 1 and 0 arguments to merge are backwards, too.  But I switched them and still got NaNs.

**Comment by mandli** [comment]
I fixed some things and switched methods for dealing with the normal and transverse components.  There were some issues with the test case that I have corrected but things are still not working with bathymetry.  I will continue to look into it.

**Comment by ketch** [comment]
I believe this is ready to merge now.

**Pull request merged**
