### PR TITLE
Improvements to and new solvers for LWR traffic model.

### PR DESCRIPTION
**Pull request by ketch**
Fix minor bugs in rp1_traffic.f90.
Fix major bugs in rp1_traffic_vc.f90 (complete rewrite).
Add new rp1_traffic_vc_tracer.f90 (includes tracer for vehicle trajectories).

Thanks to Lisa Davis for writing parts of these.

### CODE REVIEW

**Comment by ketch** [comment]
Note that the new variable-coefficient solvers don't use the f-wave approach, so any old code will need to be modified to use the new solvers.  The old solver was buggy (did not correctly handle transonic rarefactions), so it's a good idea to switch.

**Comment by ketch** [comment]
Today I realized that the new solvers in this PR are wrong.  I'm fixing them.

**Comment by mandli** [comment]
I tried these out and did not see anything off-hand wrong with them...  Should we revert the PR then?

**Comment by ketch** [comment]
Yeah.  Glad to know I'm not the only one that I fooled. :)

**Comment by mandli** [comment]
Who would ever want to change the speed limit?

**Pull request merged**
