### PR TITLE
Update LWR traffic solvers.

### PR DESCRIPTION
**Pull request by ketch**
Substantive changes:
- Fix minor bugs in exist traffic solvers.
- Change variable-coefficient traffic solver to not use f-waves
  (though it still computes fluctuations by splitting the flux difference).
- Add variable-coefficient traffic solver with tracer.

Cosmetic changes:
- Use newer variable names (e.g. num_eqn instead of meqn)
- Link to online docs for Riemann API
- Remove discussion of ql, qr since it appears online
- Use implicit none
- Use intent statements
- Place documentation at top of file
- Use 4-space indentation
- Include counts and enumeration of conserved quantities, aux variables, etc. in documentation.

### CODE REVIEW

**Comment by ketch** [comment]
In this PR and in https://github.com/clawpack/doc/pull/146, I'm pushing to use the newer names (now standard for several years) like `num_eqn`, `num_aux`, `num_cells`, etc. in the Riemann solver subroutines.  It's true that the older names (`meqn` and such) are still used in lots of other Fortran code, but I think it would be worthwhile to move to the new names in the Riemann solvers.  I think users will be more familiar with those names since they use them in their PyClaw scripts and in `setrun.py`.  Furthermore, the new variable names are used throughout the Fortran code in `clawpack/pyclaw/src/pyclaw/classic/` and the sister directory `/sharpclaw`.

As one exception we may want to keep `mx, my, mz` for the scalar integers since `num_cells` is a vector.

**Comment by mandli** [comment]
+1 on the name changes.

**Comment by mandli** [comment]
This looks good to me based on running the example in PyClaw.  I would merge this but now I am scared that I won't check it adequately :)

**Comment by ketch** [comment]
Hah, perhaps I am like those people on the LIGO team who insert fake data to see if their colleagues fall for it...

**Comment by mandli** [comment]
That's right, they did do that!  Now I am even more paranoid, make @rjleveque do it.

**Comment by mandli** [comment]
Oops, did it anyway.

**Pull request merged**
