### PR TITLE
Shallow water tracer

### PR DESCRIPTION
**Pull request by ketch**
Adds a Riemann solver for shallow water with a passive tracer, and cleans up the existing shallow water Roe solver.  All credit for this goes to @rjleveque .

### CODE REVIEW

**Comment by ketch** [comment]
I think this is now ready to merge.

**Comment by mandli** [comment]
I don't think there is a test for this Riemann solve in PyClaw (the fwave solver is tested there).  We may want to add one before merging this.

**Comment by ketch** [comment]
That is a good point.  However, we do have a test for this now in the book: https://github.com/ketch/riemann_book/blob/334dd1864d294a2bac9a7da04ebd268d4a666b73/Shallow_tracer.ipynb

That repo now has Travis CI testing too.  I could copy that example to PyClaw, but I'm inclined to just leave it where it is and consider that good enough.  What do you think?

**Comment by ketch** [comment]
The test for the book PR is failing because this PR hasn't been merged.  I'm going to merge this but look for further comments from @mandli or others on whether this is sufficient testing.

**Comment by mandli** [comment]
As long as there is at least one test somewhere I am fine with this (also have to steal that testing script for my own notebooks).

**Comment by mandli** [comment]
Beat me to the merge :)

**Pull request merged**
